import { Material, Stat } from './types';

export const MATERIALS: Material[] = [
  {
    id: '1',
    title: 'Advanced Data Structures: Comprehensive Finals Prep',
    description: 'Complete set of notes covering B-Trees, Graph Theory, and Red-Black Tree optimizations.',
    type: 'swap',
    subject: 'Computer Science',
    authorId: 'user1',
    authorName: 'Alex Rivers',
    authorAvatar: 'https://picsum.photos/seed/alex/32/32',
    rating: 4.9,
    downloads: 42,
    isVerified: true,
    icon: 'description',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: '2',
    title: 'Global Market Trends & Fiscal Policy Analysis 2024',
    description: 'Detailed breakdown of current inflation metrics and central bank interventions.',
    type: 'sell',
    subject: 'Macroeconomics',
    price: 12.50,
    authorId: 'user2',
    authorName: 'Sarah Chen',
    authorAvatar: 'https://picsum.photos/seed/sarah/32/32',
    rating: 4.7,
    downloads: 128,
    icon: 'article',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: '3',
    title: 'Cognitive Behavioral Patterns: Case Study Portfolio',
    description: 'Research paper exploring patient response to diverse therapeutic frameworks.',
    type: 'donate',
    subject: 'Psychology',
    authorId: 'user3',
    authorName: 'Prof. James Miller',
    authorAvatar: 'https://picsum.photos/seed/james/32/32',
    rating: 4.5,
    downloads: 85,
    icon: 'picture_as_pdf',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: '4',
    title: 'Quantum Mechanics: Problem Set Solutions',
    description: 'Step-by-step solutions for advanced wave functions and probability density problems.',
    type: 'swap',
    subject: 'Physics',
    authorId: 'user4',
    authorName: 'Mia K.',
    authorAvatar: 'https://picsum.photos/seed/mia/32/32',
    rating: 5.0,
    downloads: 15,
    icon: 'quiz',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: '5',
    title: 'The Ethics of AI: Philosophical Foundations',
    description: 'Exploring utilitarian vs deontological approaches to modern machine learning ethics.',
    type: 'sell',
    subject: 'Philosophy',
    price: 5.00,
    authorId: 'user5',
    authorName: 'Liam Thorne',
    authorAvatar: 'https://picsum.photos/seed/liam/32/32',
    rating: 4.8,
    downloads: 56,
    icon: 'school',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    id: '6',
    title: 'Contract Law: Key Clauses & Case Precedents',
    description: 'Summarized notes on enforceable agreements, tort law, and liability waivers.',
    type: 'donate',
    subject: 'Business Law',
    authorId: 'user6',
    authorName: 'Emma Volkov',
    authorAvatar: 'https://picsum.photos/seed/emma/32/32',
    rating: 4.6,
    downloads: 23,
    isVerified: true,
    icon: 'analytics',
    status: 'available',
    createdAt: new Date().toISOString()
  },
];

export const DASHBOARD_STATS: Stat[] = [
  { label: 'Total Uploads', value: 24, change: '+12%', icon: 'upload_file', color: 'primary' },
  { label: 'Total Earnings', value: '₹124.50', change: '+₹42.50', icon: 'payments', color: 'secondary' },
  { label: 'Donation Impact', value: 12, icon: 'volunteer_activism', color: 'tertiary' },
  { label: 'Impact Score', value: 842, icon: 'auto_awesome', color: 'primary' },
];
